---
controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_cont:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ['left_wheel_joint']
      right_wheel_names: ['right_wheel_joint']
      publish_rate: 50.0
      base_frame_id: base_link
      wheel_separation: 0.55
      wheel_radius: 0.1
      use_stamped_vel: false
